# Generated by Django 5.2.4 on 2025-07-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('serial_no', models.IntegerField()),
                ('spec', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('checked_in', models.BooleanField(default=False)),
                ('sold_out', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.productcategory')),
            ],
        ),
    ]
