# Generated by Django 5.2.4 on 2025-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_color_product_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.BigIntegerField(),
        ),
    ]
