# Generated by Django 5.2.4 on 2025-07-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(max_length=20),
        ),
    ]
