# Generated by Django 5.2.4 on 2025-07-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.ManyToManyField(related_name='color', to='store.colour'),
        ),
    ]
