# Generated by Django 5.2.4 on 2025-07-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spec',
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
