# Generated by Django 5.2.4 on 2025-07-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_spec_product_ram_product_rom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Used', 'Used'), ('UK', 'UK'), ('China', 'China')], max_length=8, null=True),
        ),
    ]
